// <auto-generated />
using System;
using HumanResourceManagementSystem.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResourceManagementSystem.Migrations
{
    [DbContext(typeof(HRMSystemDbContext))]
    [Migration("20221018045213_newupdate")]
    partial class newupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HumanResourceManagementSystem.Models.Entities.AddressInfo", b =>
                {
                    b.Property<int>("AddressInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressInfoID"), 1L, 1);

                    b.Property<string>("AEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressInfoID");

                    b.ToTable("addressInfo");
                });

            modelBuilder.Entity("HumanResourceManagementSystem.Models.Entities.CivilInfo", b =>
                {
                    b.Property<int>("CivilInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CivilInfoID"), 1L, 1);

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanCard")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CivilInfoID");

                    b.ToTable("civilInfo");
                });

            modelBuilder.Entity("HumanResourceManagementSystem.Models.Entities.EducationalInfo", b =>
                {
                    b.Property<int>("EducationalInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationalInfoID"), 1L, 1);

                    b.Property<string>("AEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BMarks")
                        .HasColumnType("int");

                    b.Property<string>("MDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MMarks")
                        .HasColumnType("int");

                    b.HasKey("EducationalInfoID");

                    b.ToTable("educationalInfo");
                });

            modelBuilder.Entity("HumanResourceManagementSystem.Models.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"), 1L, 1);

                    b.Property<int>("AddressInfoID")
                        .HasColumnType("int");

                    b.Property<int>("CivilInfoID")
                        .HasColumnType("int");

                    b.Property<int>("EducationalInfoID")
                        .HasColumnType("int");

                    b.Property<int>("OfficialInfoID")
                        .HasColumnType("int");

                    b.Property<int>("PersonalInfoID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("AddressInfoID");

                    b.HasIndex("CivilInfoID");

                    b.HasIndex("EducationalInfoID");

                    b.HasIndex("OfficialInfoID");

                    b.HasIndex("PersonalInfoID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("HumanResourceManagementSystem.Models.Entities.OfficialInfo", b =>
                {
                    b.Property<int>("OfficialInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficialInfoID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficialInfoID");

                    b.ToTable("officialInfo");
                });

            modelBuilder.Entity("HumanResourceManagementSystem.Models.Entities.PersonalInfo", b =>
                {
                    b.Property<int>("PersonalInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalInfoID"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalInfoID");

                    b.ToTable("personalInfo");
                });

            modelBuilder.Entity("HumanResourceManagementSystem.Models.Entities.Employee", b =>
                {
                    b.HasOne("HumanResourceManagementSystem.Models.Entities.AddressInfo", "AddressInfo")
                        .WithMany()
                        .HasForeignKey("AddressInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagementSystem.Models.Entities.CivilInfo", "CivilInfo")
                        .WithMany()
                        .HasForeignKey("CivilInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagementSystem.Models.Entities.EducationalInfo", "EducationalInfo")
                        .WithMany()
                        .HasForeignKey("EducationalInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagementSystem.Models.Entities.OfficialInfo", "OfficialInfo")
                        .WithMany()
                        .HasForeignKey("OfficialInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagementSystem.Models.Entities.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressInfo");

                    b.Navigation("CivilInfo");

                    b.Navigation("EducationalInfo");

                    b.Navigation("OfficialInfo");

                    b.Navigation("PersonalInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
